functionsDirectory = "netlify/functions"
plugins = []
headers = []

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {}
  force = false

[build]
  publish = "dist"
  command = "vite build"
  functions = "netlify/functions"

[database]

  [database.migrations]
    path = "netlify/database/migrations"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[functions]

  [functions."*"]
